"""Ganti FileShare dengan UserAccess dan tambahkan is_private

Revision ID: 1e98122a4d22
Revises: 67e65babccf4
Create Date: 2025-11-08 13:20:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1e98122a4d22'
down_revision = '67e65babccf4' # Pastikan ini adalah revisi 'upgrade' Anda sebelumnya
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Buat tabel baru (user_access)
    op.create_table('user_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('authorized_user_id', sa.Integer(), nullable=False),
    sa.Column('granted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['authorized_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'authorized_user_id', name='unique_user_access')
    )
    
    # 2. Hapus tabel lama (file_shares)
    # Ini akan secara otomatis menghapus index dan foreign key-nya
    op.drop_table('file_shares')
    
    # 3. Tambahkan kolom baru ke 'users'
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_private', sa.Boolean(), nullable=False, server_default=sa.true()))

    # 4. Hapus relasi lama dari 'files' (jika masih ada)
    # Kita tidak perlu melakukan ini secara eksplisit jika tabelnya sudah dihapus

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Buat kembali tabel 'file_shares' yang lama
    op.create_table('file_shares',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('file_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('owner_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('shared_with_user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('permission', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('shared_at', mysql.DATETIME(), nullable=False),
    sa.Column('accessed_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], name='file_shares_ibfk_1'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='file_shares_ibfk_2'),
    sa.ForeignKeyConstraint(['shared_with_user_id'], ['users.id'], name='file_shares_ibfk_3'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4'
    )
    # Buat kembali index yang lama
    op.create_index('unique_file_share', 'file_shares', ['file_id', 'shared_with_user_id'], unique=True)
    
    # 2. Hapus tabel baru
    op.drop_table('user_access')
    
    # 3. Hapus kolom baru dari 'users'
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_private')

    # ### end Alembic commands ###