"""Re-add session_key and add salt for hybrid crypto

Revision ID: 67e65babccf4
Revises: e169c4933fc7
Create Date: 2025-11-08 12:19:44.548105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67e65babccf4'
down_revision = 'e169c4933fc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salt', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_column('salt')

    # ### end Alembic commands ###
