"""Menambahkan kolom is_private yang hilang ke tabel users

Revision ID: 6ea41a528990
Revises: 1e98122a4d22
Create Date: 2025-11-08 13:46:04.508449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ea41a528990'
down_revision = '1e98122a4d22'
branch_labels = None
depends_on = None


def upgrade():
    # Skip adding is_private column as it already exists
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_private')

    # ### end Alembic commands ###
