"""Add encrypted_key and upload_date fields to File model

Revision ID: c1436fe01e13
Revises: cdc444843ebc
Create Date: 2025-10-24 21:39:26.038750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1436fe01e13'
down_revision = 'cdc444843ebc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encrypted_key', sa.String(length=512), nullable=False))
        batch_op.add_column(sa.Column('upload_date', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_column('upload_date')
        batch_op.drop_column('encrypted_key')

    # ### end Alembic commands ###
