"""Create all tables: users, files, reports, shares, logs

Revision ID: cdc444843ebc
Revises: 
Create Date: 2025-10-24 20:16:53.419031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdc444843ebc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('session_key', sa.String(length=256), nullable=True),
    sa.Column('profile_picture_path', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_uuid', sa.String(length=36), nullable=False),
    sa.Column('original_filename', sa.String(length=256), nullable=False),
    sa.Column('encrypted_filename', sa.String(length=256), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('encrypted_size', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('encryption_algorithm', sa.String(length=10), nullable=False),
    sa.Column('cipher_mode', sa.String(length=10), nullable=True),
    sa.Column('iv', sa.String(length=256), nullable=True),
    sa.Column('encryption_time', sa.Float(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_files_file_uuid'), ['file_uuid'], unique=True)

    op.create_table('crypto_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operation', sa.String(length=20), nullable=False),
    sa.Column('algorithm', sa.String(length=10), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('execution_time', sa.Float(), nullable=False),
    sa.Column('data_size', sa.Integer(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crypto_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crypto_logs_timestamp'), ['timestamp'], unique=False)

    op.create_table('file_shares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('shared_with_user_id', sa.Integer(), nullable=False),
    sa.Column('permission', sa.String(length=20), nullable=False),
    sa.Column('shared_at', sa.DateTime(), nullable=False),
    sa.Column('accessed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shared_with_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_id', 'shared_with_user_id', name='unique_file_share')
    )
    op.create_table('financial_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=True),
    sa.Column('encrypted_revenue', sa.Text(), nullable=True),
    sa.Column('encrypted_expenses', sa.Text(), nullable=True),
    sa.Column('encrypted_profit', sa.Text(), nullable=True),
    sa.Column('encrypted_assets', sa.Text(), nullable=True),
    sa.Column('encrypted_liabilities', sa.Text(), nullable=True),
    sa.Column('encrypted_equity', sa.Text(), nullable=True),
    sa.Column('encryption_algorithm', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('financial_reports')
    op.drop_table('file_shares')
    with op.batch_alter_table('crypto_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crypto_logs_timestamp'))

    op.drop_table('crypto_logs')
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_files_file_uuid'))

    op.drop_table('files')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
