"""Add parsed_filename column to File model

Revision ID: e169c4933fc7
Revises: c1436fe01e13
Create Date: 2025-11-08 10:23:16.795074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e169c4933fc7'
down_revision = 'c1436fe01e13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parsed_filename', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_column('parsed_filename')

    # ### end Alembic commands ###
