"""create connections table for two way user connections

Revision ID: eb23ef520ac8
Revises: 6ea41a528990
Create Date: 2025-11-08 18:43:16.032289

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eb23ef520ac8'
down_revision = '6ea41a528990'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.alter_column('salt',
               existing_type=mysql.VARCHAR(length=32),
               nullable=False)
        batch_op.drop_column('encrypted_key')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encrypted_key', mysql.VARCHAR(length=512), nullable=False))
        batch_op.alter_column('salt',
               existing_type=mysql.VARCHAR(length=32),
               nullable=True)

    op.drop_table('connections')
    # ### end Alembic commands ###
